# Generated by Django 3.1.2 on 2020-12-23 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StudentId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=30, verbose_name='Name')),
                ('t_dob', models.DateField(null=True, verbose_name='Date of Birth')),
                ('t_address', models.CharField(max_length=50, verbose_name='Address')),
                ('t_phonenum', models.CharField(max_length=20, verbose_name='Phone Number:')),
                ('t_email', models.CharField(max_length=30, verbose_name='E-mail')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teacherposition')),
                ('subject', models.ManyToManyField(to='school.Subject')),
                ('teacher_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.teacherid')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=30, verbose_name='Name')),
                ('s_dob', models.DateField(null=True, verbose_name='Date of Birth')),
                ('s_address', models.CharField(max_length=50, verbose_name='Address')),
                ('s_phonenum', models.CharField(max_length=20, verbose_name='Phone Number:')),
                ('s_email', models.CharField(max_length=30, verbose_name='E-mail')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.studentclass')),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.studentid')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teacherid')),
            ],
        ),
    ]
